"""The customManagers regex is the one piece of Renovate config that is easy
to get subtly wrong: a loose version group bumps golden-github pins to
golden-infra tags. These tests run the regex, and resolve the templates, the
same way Renovate does."""

import json
import re
from pathlib import Path

PRESET = json.loads((Path(__file__).parent.parent / "default.json").read_text())
MANAGER = PRESET["customManagers"][0]

FLAKE = """{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    golden-engine.url = "github:Fomiller/flake-hub?dir=golden-engine&ref=refs/tags/golden-engine-0.1.0";
    golden-github.url = "github:Fomiller/flake-hub?dir=golden-github&ref=refs/tags/golden-github-1.2.3";
  };
}
"""


def to_python_re(pattern: str) -> str:
    """Renovate runs these patterns through JS. Python spells the same two
    constructs differently, so translate rather than keeping a second copy of
    the pattern that could drift from the one Renovate actually uses."""
    pattern = re.sub(r"\(\?<(?![=!])", "(?P<", pattern)
    return re.sub(r"\\k<(\w+)>", r"(?P=\1)", pattern)


def deps():
    """Renovate builds a dep from the named capture groups, then lets any
    *Template field overwrite the field of the same name. Resolving templates
    against the groups alone would hide exactly that overwrite."""
    out = []
    for pattern in MANAGER["matchStrings"]:
        for m in re.finditer(to_python_re(pattern), FLAKE, re.MULTILINE):
            dep = dict(m.groupdict())
            for field in ("depName", "packageName", "datasource", "versioning"):
                template = MANAGER.get(f"{field}Template")
                if template is not None:
                    dep[field] = template
            out.append(dep)
    return out


def render(template: str, dep: dict) -> str:
    return re.sub(r"\{\{\{(\w+)\}\}\}", lambda m: dep[m.group(1)], template)


def test_every_pack_pin_is_matched():
    assert len(deps()) == 2


def test_current_value_is_the_full_prefixed_tag():
    assert sorted(d["currentValue"] for d in deps()) == [
        "golden-engine-0.1.0",
        "golden-github-1.2.3",
    ]


def test_datasource_is_github_tags_on_the_hub():
    assert MANAGER["datasourceTemplate"] == "github-tags"
    assert MANAGER["packageNameTemplate"] == "Fomiller/flake-hub"


def test_extract_version_is_anchored_to_the_pack_directory():
    """Without the per-pack anchor, a golden-infra tag is a candidate upgrade
    for a golden-github pin, because both are tags on the same repo. This is
    why the pack name must reach extractVersionTemplate as depName: setting
    depNameTemplate would overwrite it with the repo slug and the anchor would
    match no tag at all."""
    for dep in deps():
        resolved = render(MANAGER["extractVersionTemplate"], dep)
        assert resolved.startswith(f"^{dep['currentValue'].rsplit('-', 1)[0]}-")
        assert re.match(to_python_re(resolved), dep["currentValue"]).group("version") is not None


def test_a_pin_only_matches_when_the_directory_and_the_tag_prefix_agree():
    """The \\k<depName> backreference is what stops a golden-github directory
    pinned to a golden-infra tag from being treated as a valid pin."""
    crossed = FLAKE.replace(
        "dir=golden-github&ref=refs/tags/golden-github-1.2.3",
        "dir=golden-github&ref=refs/tags/golden-infra-1.2.3",
    )
    pattern = to_python_re(MANAGER["matchStrings"][0])
    assert len(re.findall(pattern, crossed, re.MULTILINE)) == 1


def test_nix_manager_is_disabled():
    """flake.lock is regenerated by the consumer's own workflow. Letting
    Renovate's nix manager also touch it produces two conflicting bumps."""
    assert PRESET["nix"]["enabled"] is False
