name: Docs

on:
  push:
    branches: [main]
    paths: ['docs/**', '.github/workflows/docs.yaml']

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    uses: Fomiller/gh-actions/.github/workflows/mdbook.yaml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      book-path: docs
